//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EVCS
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class EVCSEntities1 : DbContext
    {
        public EVCSEntities1()
            : base("name=EVCSEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<CarInfos> CarInfos { get; set; }
        public DbSet<Records> Records { get; set; }
        public DbSet<SerialNumber> SerialNumber { get; set; }
        public DbSet<SerialNumberRecords> SerialNumberRecords { get; set; }
        public DbSet<Singlevolume> Singlevolume { get; set; }
        public DbSet<V_Records_Dayly_Volume> V_Records_Dayly_Volume { get; set; }
        public DbSet<CarTasks> CarTasks { get; set; }
        public DbSet<PersonTasks> PersonTasks { get; set; }
        public DbSet<Users> Users { get; set; }
        public DbSet<Count> Count { get; set; }
        public DbSet<VolumeDetail> VolumeDetail { get; set; }
    }
}
