//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EVCS
{
    using System;
    using System.Collections.Generic;
    
    public partial class SerialNumber
    {
        public int ID { get; set; }
        public string Prefix { get; set; }
        public string DateFormat { get; set; }
        public Nullable<int> Increment { get; set; }
        public Nullable<int> Init { get; set; }
        public Nullable<int> Length { get; set; }
        public Nullable<int> CurrentValue { get; set; }
    }
}
